/*
 * Generated Java Source
 * Do not edit this file.
 */
import ej.junit.AbstractAllTestClassesWrapper;
import ej.junit.CheckHelperTestListener;

@SuppressWarnings("all")
public class _AllTestClasses extends AbstractAllTestClassesWrapper {

	protected void runTestClasses() {
		wrapperRunTestClass(new _AllTests_FirstTest());

	}

	public static void main(String[] args) {
		new _AllTestClasses().run(new CheckHelperTestListener());
	}	
}