/*
 * Generated Java Source
 * Do not edit this file.
 */
import ej.junit.AbstractTestWrapper;
import ej.junit.CheckHelperTestListener;

import org.junit.jupiter.api.Test;


@SuppressWarnings("all")
public class _SingleTest_FirstTest_test extends AbstractTestWrapper {

	public _SingleTest_FirstTest_test() {
		super(FirstTest.class);
	}

	protected void runBeforeClassMethods() throws Exception {
	}

	protected void runAfterClassMethods() throws Exception {
	}

	protected void runBeforeMethods() throws Exception {
	}

	protected void runAfterMethods() throws Exception {
	}

	protected void runTestMethods() {
		_run_test();

	}

	private void _run_test() {
		boolean ok = false;
		try {
			if (testInitialize("test")) {
				((FirstTest)test).test();
				ok = true;
			}
		} catch(AssertionError e) {
			reportFailure(e);
		} catch(Throwable t) {
			reportError(t);
		} finally {
			testFinalize(ok);
		}
	}

	public static void main(String[] args) {
		new _SingleTest_FirstTest_test().run(new CheckHelperTestListener());
	}	
}