/*
 * Generated Java Source
 * Do not edit this file.
 */
import ej.junit.AbstractTestWrapper;
import ej.junit.CheckHelperTestListener;

import org.junit.Assert;
import org.junit.Test;


@SuppressWarnings("all")
public class _SingleTest_FirstTest_fail extends AbstractTestWrapper {

	public _SingleTest_FirstTest_fail() {
		super(FirstTest.class);
	}

	protected void runBeforeClassMethods() throws Exception {
	}

	protected void runAfterClassMethods() throws Exception {
	}

	protected void runBeforeMethods() throws Exception {
	}

	protected void runAfterMethods() throws Exception {
	}

	protected void runTestMethods() {
		_run_fail();

	}

	private void _run_fail() {
		boolean ok = false;
		try {
			if (testInitialize("fail")) {
				((FirstTest)test).fail();
				ok = true;
			}
		} catch(AssertionError e) {
			reportFailure(e);
		} catch(Throwable t) {
			reportError(t);
		} finally {
			testFinalize(ok);
		}
	}

	public static void main(String[] args) {
		new _SingleTest_FirstTest_fail().run(new CheckHelperTestListener());
	}	
}